/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Perform a health check on the API */
    get: operations["healthcheck"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/assets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a list of assets */
    get: operations["getAssets"];
    put?: never;
    /** Create a new asset */
    post: operations["createAsset"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  [path: `/assets/${string}`]: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    /** Retrieve an asset by its ID */
    get: operations["getAssetById"];
    put?: never;
    post?: never;
    /** Delete an asset by its ID */
    delete: operations["deleteAssetById"];
    options?: never;
    head?: never;
    /** Update an asset by its ID */
    patch: operations["patchAssetById"];
    trace?: never;
  };
  [path: `/assets/${string}/comments`]: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    /** Retrieve all comments for a specific asset */
    get: operations["getCommentsByAssetId"];
    put?: never;
    /** Create a new comment on a specific asset */
    post: operations["createCommentByAssetId"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  [path: `/assets/${string}/like`]: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Toggle like status for an asset */
    post: operations["likeAssetById"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/collections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve a list of collections */
    get: operations["getCollections"];
    put?: never;
    /** Create a new collection */
    post: operations["createCollection"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  [path: `/collections/${string}`]: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: components["parameters"]["collectionIdPathParam"];
      };
      cookie?: never;
    };
    /** Retrieve a collection by its ID */
    get: operations["getCollectionById"];
    put?: never;
    post?: never;
    /** Delete a collection by its ID */
    delete: operations["deleteCollectionById"];
    options?: never;
    head?: never;
    /** Update a collection by its ID */
    patch: operations["patchCollectionById"];
    trace?: never;
  };
  [path: `/collections/${string}/assets`]: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: components["parameters"]["collectionIdPathParam"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add a list of assets to a collection */
    post: operations["addAssetsToCollection"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  [path: `/collections/${string}/assets/remove`]: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: components["parameters"]["collectionIdPathParam"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Remove a list of assets from a collection */
    post: operations["removeAssetsFromCollection"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  [path: `/comments/${string}`]: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["commentIdPathParam"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a specific comment by its ID */
    delete: operations["deleteCommentById"];
    options?: never;
    head?: never;
    /** Update a specific comment by its ID */
    patch: operations["patchCommentById"];
    trace?: never;
  };
  [path: `/users/${string}`]: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["userIdPathParam"];
      };
      cookie?: never;
    };
    /** Retrieve a user by their ID */
    get: operations["getUserById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Retrieve the current user */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the current user */
    patch: operations["patchCurrentUser"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    asset: components["schemas"]["userSummary"] & {
      /** Format: uuid */
      assetId: string;
      assetType: components["schemas"]["assetType"];
      commentCount: number;
      /** Format: date-time */
      createdAt: string;
      description: string;
      /** Format: uri */
      imageUrl: string;
      isLikedByCurrentUser: boolean;
      likeCount: number;
      name: string;
      /** Format: date-time */
      updatedAt: string;
      visibility: components["schemas"]["visibility"];
    };
    assetData:
      | components["schemas"]["character"]
      | components["schemas"]["location"]
      | components["schemas"]["quest"]
      | components["schemas"]["map"];
    assetDataCreate:
      | components["schemas"]["characterCreate"]
      | components["schemas"]["locationCreate"]
      | components["schemas"]["questCreate"]
      | components["schemas"]["mapCreate"];
    /** @enum {string} */
    assetType: "character" | "location" | "quest" | "map";
    character: {
      abilities: string;
      /** @enum {string} */
      alignment:
        | "lawful_good"
        | "neutral_good"
        | "chaotic_good"
        | "lawful_neutral"
        | "true_neutral"
        | "chaotic_neutral"
        | "lawful_evil"
        | "neutral_evil"
        | "chaotic_evil";
      appearance: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      assetType: "character";
      background: string;
      /** @enum {string} */
      class:
        | "barbarian"
        | "bard"
        | "cleric"
        | "druid"
        | "fighter"
        | "monk"
        | "paladin"
        | "ranger"
        | "rogue"
        | "sorcerer"
        | "warlock"
        | "wizard";
      equipment: string;
      /** @enum {string} */
      gender: "male" | "female" | "non_binary" | "genderfluid" | "agender";
      motivation: string;
      notes: string;
      personality: string;
      /** @enum {string} */
      race:
        | "human"
        | "elf"
        | "drow"
        | "half_elf"
        | "half_orc"
        | "halfling"
        | "dwarf"
        | "gnome"
        | "tiefling"
        | "githyanki"
        | "dragonborn";
    };
    characterCreate: {
      abilities?: string;
      /** @enum {string} */
      alignment:
        | "lawful_good"
        | "neutral_good"
        | "chaotic_good"
        | "lawful_neutral"
        | "true_neutral"
        | "chaotic_neutral"
        | "lawful_evil"
        | "neutral_evil"
        | "chaotic_evil";
      appearance?: string;
      background?: string;
      /** @enum {string} */
      class:
        | "barbarian"
        | "bard"
        | "cleric"
        | "druid"
        | "fighter"
        | "monk"
        | "paladin"
        | "ranger"
        | "rogue"
        | "sorcerer"
        | "warlock"
        | "wizard";
      equipment?: string;
      /** @enum {string} */
      gender: "male" | "female" | "non_binary" | "genderfluid" | "agender";
      motivation?: string;
      notes?: string;
      personality?: string;
      /** @enum {string} */
      race:
        | "human"
        | "elf"
        | "drow"
        | "half_elf"
        | "half_orc"
        | "halfling"
        | "dwarf"
        | "gnome"
        | "tiefling"
        | "githyanki"
        | "dragonborn";
    };
    collection: components["schemas"]["userSummary"] & {
      assetCount: number;
      /** Format: uuid */
      collectionId: string;
      coverImageUrl: string | null;
      /** Format: date-time */
      createdAt: string;
      description: string;
      name: string;
      /** Format: date-time */
      updatedAt: string;
      visibility: components["schemas"]["visibility"];
    };
    comment: components["schemas"]["userSummary"] & {
      body: string;
      /** Format: uuid */
      commentId: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    location: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      assetType: "location";
      atmosphere: string;
      climate: string;
      dangerLevel: string;
      inhabitants: string;
      locationType: string;
      narrativeRole: string;
      notes: string;
      pointsOfInterest: string;
      terrain: string;
    };
    locationCreate: {
      atmosphere?: string;
      climate?: string;
      dangerLevel?: string;
      inhabitants?: string;
      locationType: string;
      narrativeRole?: string;
      notes?: string;
      pointsOfInterest?: string;
      terrain?: string;
    };
    map: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      assetType: "map";
      mapType: string;
      notes: string;
      pointsOfInterest: string;
      scale: string;
      terrain: string;
    };
    mapCreate: {
      mapType: string;
      notes?: string;
      pointsOfInterest?: string;
      scale?: string;
      terrain?: string;
    };
    quest: {
      antagonist: string;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      assetType: "quest";
      complexity: string;
      hasCombat: boolean;
      hasDilemmas: boolean;
      hasPuzzles: boolean;
      hasSkillChallenges: boolean;
      location: string;
      notableNPCs: string;
      notes: string;
      objective: string;
      questType: string;
      tone: string;
    };
    questCreate: {
      antagonist?: string;
      complexity?: string;
      hasCombat: boolean;
      hasDilemmas: boolean;
      hasPuzzles: boolean;
      hasSkillChallenges: boolean;
      location?: string;
      notableNPCs?: string;
      notes?: string;
      objective?: string;
      questType: string;
      tone?: string;
    };
    userSummary: {
      displayName: string;
      /** Format: uuid */
      userId: string;
    };
    /** @enum {string} */
    visibility: "public" | "private" | "unlisted";
  };
  responses: {
    /** @description OK */
    AssetDetails: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["asset"] & {
          data: components["schemas"]["assetData"];
        };
      };
    };
    /** @description OK */
    AssetLike: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          /** Format: uuid */
          assetId: string;
          isLikedByCurrentUser: boolean;
          likeCount: number;
        };
      };
    };
    /** @description OK */
    AssetList: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          assets: components["schemas"]["asset"][];
        };
      };
    };
    /** @description OK */
    CollectionDetails: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["collection"] & {
          assets: components["schemas"]["asset"][];
        };
      };
    };
    /** @description OK */
    CollectionList: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          collections: components["schemas"]["collection"][];
        };
      };
    };
    /** @description OK */
    CommentDetails: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["comment"];
      };
    };
    /** @description OK */
    CommentList: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          comments: components["schemas"]["comment"][];
        };
      };
    };
    /** @description Standard error response */
    ErrorResponse: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            code: number;
            message: string;
          };
          /** @enum {string} */
          status: "error";
        };
      };
    };
    /** @description Health check response */
    HealthCheck: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          /** Format: uri */
          githubUrl: string;
          hostname: string;
          /** @enum {string} */
          status: "ok";
          /** Format: date-time */
          timestamp: string;
          version: string;
        };
      };
    };
    /** @description OK */
    UserDetails: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          bio: string;
          /** Format: date-time */
          createdAt: string;
          displayName: string;
          /** Format: date-time */
          updatedAt: string;
          /** Format: uuid */
          userId: string;
        };
      };
    };
  };
  parameters: {
    assetIdPathParam: string;
    assetTypeQueryParam: components["schemas"]["assetType"];
    collectionIdPathParam: string;
    collectionIdQueryParam: string;
    commentIdPathParam: string;
    descriptionQueryParam: string;
    limitQueryParam: number;
    nameQueryParam: string;
    offsetQueryParam: number;
    userIdPathParam: string;
    userIdQueryParam: string;
  };
  requestBodies: {
    assetCreate: {
      content: {
        "application/json": {
          assetType: components["schemas"]["assetType"];
          data: components["schemas"]["assetDataCreate"];
          name: string;
          visibility: components["schemas"]["visibility"];
        };
      };
    };
    assetIds: {
      content: {
        "application/json": {
          assetIds: string[];
        };
      };
    };
    assetUpdate: {
      content: {
        "application/json": {
          description?: string;
          name?: string;
          visibility?: components["schemas"]["visibility"];
        };
      };
    };
    collectionCreateAndUpdate: {
      content: {
        "application/json": {
          description?: string;
          name: string;
          visibility?: components["schemas"]["visibility"];
        };
      };
    };
    commentCreateAndUpdate: {
      content: {
        "application/json": {
          body: string;
        };
      };
    };
    userUpdate: {
      content: {
        "application/json": {
          bio?: string;
          displayName?: string;
        };
      };
    };
  };
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  healthcheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["HealthCheck"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  getAssets: {
    parameters: {
      query?: {
        assetType?: components["parameters"]["assetTypeQueryParam"];
        collectionId?: components["parameters"]["collectionIdQueryParam"];
        description?: components["parameters"]["descriptionQueryParam"];
        limit?: components["parameters"]["limitQueryParam"];
        name?: components["parameters"]["nameQueryParam"];
        offset?: components["parameters"]["offsetQueryParam"];
        userId?: components["parameters"]["userIdQueryParam"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["AssetList"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  createAsset: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["assetCreate"];
    responses: {
      201: components["responses"]["AssetDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  getAssetById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["AssetDetails"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  deleteAssetById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  patchAssetById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["assetUpdate"];
    responses: {
      200: components["responses"]["AssetDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  getCommentsByAssetId: {
    parameters: {
      query?: {
        limit?: components["parameters"]["limitQueryParam"];
        offset?: components["parameters"]["offsetQueryParam"];
      };
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["CommentList"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  createCommentByAssetId: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["commentCreateAndUpdate"];
    responses: {
      201: components["responses"]["CommentDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  likeAssetById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        assetId: components["parameters"]["assetIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["AssetLike"];
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  getCollections: {
    parameters: {
      query?: {
        limit?: components["parameters"]["limitQueryParam"];
        offset?: components["parameters"]["offsetQueryParam"];
        userId?: components["parameters"]["userIdQueryParam"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["CollectionList"];
      400: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  createCollection: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["collectionCreateAndUpdate"];
    responses: {
      201: components["responses"]["CollectionDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  getCollectionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: components["parameters"]["collectionIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["CollectionDetails"];
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  deleteCollectionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: components["parameters"]["collectionIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  patchCollectionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: components["parameters"]["collectionIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["collectionCreateAndUpdate"];
    responses: {
      200: components["responses"]["CollectionDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  addAssetsToCollection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: components["parameters"]["collectionIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["assetIds"];
    responses: {
      200: components["responses"]["CollectionDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  removeAssetsFromCollection: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        collectionId: components["parameters"]["collectionIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["assetIds"];
    responses: {
      200: components["responses"]["CollectionDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  deleteCommentById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["commentIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No Content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  patchCommentById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        commentId: components["parameters"]["commentIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["commentCreateAndUpdate"];
    responses: {
      200: components["responses"]["CommentDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      403: components["responses"]["ErrorResponse"];
      404: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  getUserById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: components["parameters"]["userIdPathParam"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["UserDetails"];
      404: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: components["responses"]["UserDetails"];
      401: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
  patchCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: components["requestBodies"]["userUpdate"];
    responses: {
      200: components["responses"]["UserDetails"];
      400: components["responses"]["ErrorResponse"];
      401: components["responses"]["ErrorResponse"];
      415: components["responses"]["ErrorResponse"];
      500: components["responses"]["ErrorResponse"];
    };
  };
}
